
import java.awt.Dialog;
import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setIcon();
    }
    public static MainFrame T;
    public static SimuLCS pp;
    public static SimuBubbleSort bs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonLCS = new javax.swing.JButton();
        ButtonBubbleSort = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(470, 355));
        setMinimumSize(new java.awt.Dimension(470, 355));
        setPreferredSize(new java.awt.Dimension(470, 355));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("  Algorithm Simulator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 300, 80);

        ButtonLCS.setBackground(new java.awt.Color(153, 102, 255));
        ButtonLCS.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        ButtonLCS.setForeground(new java.awt.Color(102, 0, 102));
        ButtonLCS.setText("LCS");
        ButtonLCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLCSActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLCS);
        ButtonLCS.setBounds(60, 120, 160, 70);

        ButtonBubbleSort.setBackground(new java.awt.Color(153, 102, 255));
        ButtonBubbleSort.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        ButtonBubbleSort.setForeground(new java.awt.Color(102, 0, 102));
        ButtonBubbleSort.setText("Bubble Sort");
        ButtonBubbleSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBubbleSortActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBubbleSort);
        ButtonBubbleSort.setBounds(260, 120, 170, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\2-1 Project\\New folder\\back_new.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(475, 355));
        jLabel2.setMinimumSize(new java.awt.Dimension(475, 355));
        jLabel2.setPreferredSize(new java.awt.Dimension(475, 355));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLCSActionPerformed
        // TODO add your handling code here:
        /* Create and display the form */
        T.setEnabled(false);
        pp = new SimuLCS(T);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pp.setVisible(true);
            }
        });
    }//GEN-LAST:event_ButtonLCSActionPerformed

    private void ButtonBubbleSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBubbleSortActionPerformed
        // TODO add your handling code here:
        /* Create and display the form */
        T.setEnabled(false);
        bs = new SimuBubbleSort(T);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bs.setVisible(true);
            }
        });
    }//GEN-LAST:event_ButtonBubbleSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         T = new MainFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                T.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBubbleSort;
    private javax.swing.JButton ButtonLCS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconFrame.jpg")));
    }
}
